export type PaletteColor = {
  hex: string
  zh: string
  en: string
  hint: string
}

export const PALETTE: readonly PaletteColor[] = [
  { hex: '#C8372D', zh: '朱紅', en: 'Vermilion Red', hint: '找找看郵筒、消防栓或熟透的番茄' },
  { hex: '#A3262A', zh: '酒紅', en: 'Burgundy', hint: '找找看一杯紅酒、書封或秋天的圍巾' },
  { hex: '#E5484D', zh: '莓紅', en: 'Berry Red', hint: '找找看草莓、紅燈或一枚小貼紙' },
  { hex: '#8C1C13', zh: '棗紅', en: 'Jujube', hint: '找找看老木門、磚牆或一顆紅棗' },
  { hex: '#D9534F', zh: '珊瑚紅', en: 'Coral Red', hint: '找找看紅色的傘、鞋帶或包裝袋' },
  { hex: '#E8603C', zh: '柿子橘', en: 'Persimmon', hint: '找找看招牌、落葉或一杯熱茶' },
  { hex: '#F28C28', zh: '琥珀橘', en: 'Amber Orange', hint: '找找看橘子、施工錐或夕陽的一角' },
  { hex: '#FF9F6B', zh: '蜜桃橘', en: 'Peach Orange', hint: '找找看暖燈、桃子或牆上的光' },
  { hex: '#D2691E', zh: '焦糖橘', en: 'Caramel', hint: '找找看烤吐司、皮革或咖啡杯墊' },
  { hex: '#F4A259', zh: '杏橘', en: 'Apricot', hint: '找找看杏桃、蛋糕或路燈下的光暈' },
  { hex: '#FF7A00', zh: '南瓜橘', en: 'Pumpkin', hint: '找找看南瓜、橘貓或一件外套' },
  { hex: '#F6C453', zh: '蛋黃黃', en: 'Yolk', hint: '找找看荷包蛋、便利貼或計程車' },
  { hex: '#FFD93D', zh: '檸檬黃', en: 'Lemon', hint: '找找看檸檬、黃色雨衣或斑馬線旁的線' },
  { hex: '#E9B949', zh: '芥末黃', en: 'Mustard', hint: '找找看芥末醬、毛衣或老海報' },
  { hex: '#F7E7A0', zh: '奶油黃', en: 'Butter', hint: '找找看奶油、月光或淡黃色的牆' },
  { hex: '#FFC857', zh: '向日葵黃', en: 'Sunflower', hint: '找找看花、黃色的筆或玩具' },
  { hex: '#D4A017', zh: '蜂蜜金', en: 'Honey Gold', hint: '找找看蜂蜜、銅器或金黃的麥穗' },
  { hex: '#5E8C61', zh: '抹茶綠', en: 'Matcha', hint: '找找看抹茶、盆栽或公園長椅' },
  { hex: '#2F6B3F', zh: '森林綠', en: 'Forest', hint: '找找看樹蔭、爬藤或深色的背包' },
  { hex: '#8DB580', zh: '嫩葉綠', en: 'Young Leaf', hint: '找找看新芽、萵苣或春天的樹' },
  { hex: '#3E9B7A', zh: '薄荷綠', en: 'Mint', hint: '找找看薄荷糖、玻璃瓶或牙膏' },
  { hex: '#A7C957', zh: '青蘋果綠', en: 'Green Apple', hint: '找找看蘋果、螢光筆或草地' },
  { hex: '#6B8E23', zh: '橄欖綠', en: 'Olive', hint: '找找看橄欖、軍裝外套或路邊的葉' },
  { hex: '#1F7A6D', zh: '孔雀綠', en: 'Peacock', hint: '找找看綠色的招牌、羽毛或玻璃' },
  { hex: '#3B6FB6', zh: '牛仔藍', en: 'Denim', hint: '找找看牛仔褲、藍色的書或天空' },
  { hex: '#89C2D9', zh: '天空藍', en: 'Sky', hint: '找找看晴天、遮陽傘或一件襯衫' },
  { hex: '#1D3557', zh: '午夜藍', en: 'Midnight', hint: '找找看夜色、深色的杯子或制服' },
  { hex: '#4FB3BF', zh: '湖水藍', en: 'Lake', hint: '找找看泳池、水杯或藍色的瓷磚' },
  { hex: '#5C7AEA', zh: '矢車菊藍', en: 'Cornflower', hint: '找找看花、包裝盒或手機殼' },
  { hex: '#2A9DB8', zh: '青花藍', en: 'Cyan Porcelain', hint: '找找看瓷器、海報或藍色的貼紙' },
  { hex: '#A8C6E5', zh: '霧藍', en: 'Mist Blue', hint: '找找看霧、窗戶或淡藍色的衣服' },
  { hex: '#7B5EA7', zh: '葡萄紫', en: 'Grape', hint: '找找看葡萄、紫色的花或一支筆' },
  { hex: '#B497D6', zh: '薰衣草紫', en: 'Lavender', hint: '找找看薰衣草、糖果紙或傍晚的雲' },
  { hex: '#4B2C6F', zh: '茄子紫', en: 'Aubergine', hint: '找找看茄子、深色圍巾或夜空' },
  { hex: '#9D6BB3', zh: '紫藤', en: 'Wisteria', hint: '找找看紫藤花、雨傘或緞帶' },
  { hex: '#6A4C93', zh: '鳶尾紫', en: 'Iris', hint: '找找看花瓣、墨水瓶或標籤' },
  { hex: '#C3A6E0', zh: '藕紫', en: 'Lilac', hint: '找找看淡紫的燈、杯子或衣角' },
  { hex: '#F4A6B7', zh: '櫻花粉', en: 'Sakura', hint: '找找看櫻花、粉紅色的傘或便條' },
  { hex: '#E86A92', zh: '玫瑰粉', en: 'Rose', hint: '找找看玫瑰、糖霜或包裝紙' },
  { hex: '#FFC4D6', zh: '棉花糖粉', en: 'Cotton Candy', hint: '找找看棉花糖、氣球或貼紙' },
  { hex: '#D6336C', zh: '桃紅', en: 'Magenta', hint: '找找看桃紅色的花、海報或帽子' },
  { hex: '#F7B7A3', zh: '蜜桃粉', en: 'Blush', hint: '找找看臉頰般的粉、牆面或毛巾' },
  { hex: '#FF8FAB', zh: '草莓牛奶粉', en: 'Strawberry Milk', hint: '找找看粉紅色的飲料、鞋子或蛋糕' },
  { hex: '#7A4E2D', zh: '可可棕', en: 'Cocoa', hint: '找找看巧克力、木桌或一杯咖啡' },
  { hex: '#A47148', zh: '焦糖棕', en: 'Toffee', hint: '找找看紙袋、皮包或老木箱' },
  { hex: '#5B3A29', zh: '咖啡棕', en: 'Espresso', hint: '找找看咖啡豆、深色木頭或皮鞋' },
  { hex: '#C19A6B', zh: '駝色', en: 'Camel', hint: '找找看大衣、紙箱或沙灘上的一角' },
  { hex: '#8B5A2B', zh: '栗子棕', en: 'Chestnut', hint: '找找看栗子、樹幹或磚牆' },
  { hex: '#D2B48C', zh: '奶茶棕', en: 'Milk Tea', hint: '找找看奶茶、麻繩或牛皮紙' },
  { hex: '#2B2A28', zh: '墨黑', en: 'Ink Black', hint: '找找看影子、黑色的筆或夜裡的窗' },
  { hex: '#8E8B85', zh: '石灰灰', en: 'Stone Gray', hint: '找找看水泥牆、石頭或雨天的天空' },
  { hex: '#D9D5CC', zh: '雲霧灰', en: 'Cloud', hint: '找找看雲、紙巾或淺色的桌面' },
  { hex: '#F3EFE6', zh: '米白', en: 'Ivory', hint: '找找看瓷盤、襯衫或一張紙' },
  { hex: '#5F6B73', zh: '鉛灰藍', en: 'Slate', hint: '找找看鐵門、灰色的鞋或天橋' },
  { hex: '#B8B2A7', zh: '燕麥灰', en: 'Oat', hint: '找找看帆布袋、毛衣或碗裡的燕麥' },
  { hex: '#C2703D', zh: '赤陶', en: 'Terracotta', hint: '找找看花盆、屋瓦或一塊磚' },
  { hex: '#BC6C25', zh: '鐵鏽橘', en: 'Rust', hint: '找找看生鏽的鐵、楓葉或老招牌' },
  { hex: '#264653', zh: '深海青', en: 'Deep Sea', hint: '找找看深色的水、玻璃或一件外套' },
  { hex: '#2A9D8F', zh: '青碧', en: 'Teal', hint: '找找看青色的門、盆栽或包裝' },
  { hex: '#E76F51', zh: '朱砂橘', en: 'Cinnabar', hint: '找找看朱砂色的印章、燈籠或圍巾' },
]
